version: "{build}"

branches:
  only:
  - master

build: false

environment:
  nodejs_version: "6"
  L10N_LOCALE_SRC: locales
  L10N_LOCALE_DEST: dist/locales

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test


clone_depth: 1
